services:
  mongo:
    image: mongo:7.0.39-jammy
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    container_name: task-service
    depends_on:
      - mongo
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - '3003:3003'
    depends_on:
      - mongo
      - rabbitmq

  frontend-service:
    build: ./frontend
    container_name: frontend-service
    depends_on:
      - user-service
      - task-service
      - notification-service

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-service
      - notification-service
      - task-service
      - user-service

volumes:
  mongo-data:
